modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="strawberrymc"
version="1.0.0"
displayName="Strawberry Minecraft"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "strawberrymc.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.strawberrymc]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.strawberrymc]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration